name: Build and Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install compile dependencies
        run: sudo apt update && sudo apt install -y cmake gcc

      - uses: dtolnay/rust-toolchain@stable

      - name: Build binding
        run: cargo build

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

